project_id = "gvxqiqvqcypwvshevtec"

[functions.coin-admin]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.generate-verification-code]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.minecraft-api]
verify_jwt = false

[functions.op-admin]
verify_jwt = false